"""Add order and hide_from_menu to Page model

Revision ID: 0b7ccbfa8f7c
Revises: 8f5b2066cbac
Create Date: 2016-03-23 16:33:44.047433

"""

# revision identifiers, used by Alembic.
revision = '0b7ccbfa8f7c'
down_revision = '8f5b2066cbac'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hide_from_menu', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_column('order')
        batch_op.drop_column('hide_from_menu')

    ### end Alembic commands ###
