"""Added Section Layout Settings and Site Settings

Revision ID: 698cc06661d6
Revises: 958a9358a256
Create Date: 2016-02-29 00:03:36.777728

"""

# revision identifiers, used by Alembic.
revision = '698cc06661d6'
down_revision = '958a9358a256'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites_settings',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('setting', sa.Text(length=40), nullable=False),
    sa.Column('value', sa.Text(length=200), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('site_id', 'setting')
    )
    op.create_index(op.f('ix_sites_settings_site_id'), 'sites_settings', ['site_id'], unique=False)
    op.create_table('pages_sections_layout_settings',
    sa.Column('page_section_id', sa.Integer(), nullable=False),
    sa.Column('setting', sa.Text(length=40), nullable=False),
    sa.Column('value', sa.Text(length=200), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.ForeignKeyConstraint(['page_section_id'], ['pages_sections.id'], ),
    sa.PrimaryKeyConstraint('page_section_id', 'setting')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages_sections_layout_settings')
    op.drop_index(op.f('ix_sites_settings_site_id'), table_name='sites_settings')
    op.drop_table('sites_settings')
    ### end Alembic commands ###
