"""Add self-referential image reference

Revision ID: 8f5b2066cbac
Revises: 698cc06661d6
Create Date: 2016-03-20 19:35:31.321144

"""

# revision identifiers, used by Alembic.
revision = '8f5b2066cbac'
down_revision = '698cc06661d6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('ix_images_parent_image_id', 'images', ['parent_image_id'], ['id'])


    ### end Alembic commands ###


def downgrade():
    pass
    ### end Alembic commands ###
