"""Initial state

Revision ID: 958a9358a256
Revises: 
Create Date: 2016-02-19 23:59:35.206805

"""

# revision identifiers, used by Alembic.
revision = '958a9358a256'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
